### ISSUE TITLE
Fails with image with just a red profile.

### ISSUE THREAD

**Issue by mutterer** [ndefrancesco/macro-frenzy#1]
Hi,
I added two test images to this fork: https://github.com/mutterer/macro-frenzy
The current version works with the plot with r,g, and b profiles, but fails with the plot with only a red profile (I get a cyan profile instead).

**Comment by mutterer** [comment]
if setThreshold (0,127) selects everything then  run("Make Inverse") creates no selection. This makes the  run("Subtract...", "value=128 slice") acts on full image, and cancels the previous Add... step.
I suggest checking for selection type != -1 after  Make Inverse.
I'll file a pull request.

**Comment by ndefrancesco** [comment]
Thanks for catching that! 
Clearly, using ROIs as proxies for masks is not safe in the general case. My bad.

Maybe we should also add an if (selectionType>-1) to the first case, which although rarer, should also be covered. See the commit for the suggested change.

**Comment by mutterer** [comment]
Yes it might be safer, even if it would take just a single black, white or grey pixel to have at least one   0 value pixel in the Hue channel.

**Comment by ndefrancesco** [comment]
Done! Thanks!
